from __future__ import annotations

import argparse
import random
from collections import deque
from pathlib import Path


COLS = 30
ROWS = 21
ROUTE_FILE = "ai-cycle.lua"
DIRECTION_CHARS = {
    (1, 0): "R",
    (-1, 0): "L",
    (0, 1): "D",
    (0, -1): "U",
}


def build_cycle(cols: int, rows: int) -> list[tuple[int, int]]:
    if cols < 2 or rows < 2 or cols % 2 != 0:
        raise ValueError("The Hamiltonian cycle requires an even width and both dimensions >= 2.")

    cells = [(x, 1) for x in range(1, cols + 1)]
    cells.extend((cols, y) for y in range(2, rows + 1))
    current_y = rows

    for x in range(cols - 1, 1, -1):
        cells.append((x, current_y))
        target_y = 2 if current_y == rows else rows
        step = 1 if target_y > current_y else -1
        cells.extend((x, y) for y in range(current_y + step, target_y + step, step))
        current_y = target_y

    if current_y != rows:
        raise ValueError("The generated path cannot close along the first column.")
    cells.extend((1, y) for y in range(rows, 1, -1))
    return cells


def validate_cycle(cells: list[tuple[int, int]], cols: int, rows: int) -> str:
    expected_size = cols * rows
    if len(cells) != expected_size:
        raise ValueError(f"Expected {expected_size} cells, got {len(cells)}.")
    if len(set(cells)) != expected_size:
        raise ValueError("The route contains duplicate cells.")

    moves: list[str] = []
    for index, current in enumerate(cells):
        following = cells[(index + 1) % len(cells)]
        delta = (following[0] - current[0], following[1] - current[1])
        if delta not in DIRECTION_CHARS:
            raise ValueError(f"Cells {current} and {following} are not adjacent.")
        moves.append(DIRECTION_CHARS[delta])

    for x, y in cells:
        if not 1 <= x <= cols or not 1 <= y <= rows:
            raise ValueError(f"Cell {(x, y)} is outside the board.")
    return "".join(moves)


def render_lua(moves: str, cols: int, rows: int) -> str:
    chunks = [moves[index : index + 84] for index in range(0, len(moves), 84)]
    move_lines = []
    for index, chunk in enumerate(chunks):
        suffix = " .." if index < len(chunks) - 1 else ""
        move_lines.append(f'    "{chunk}"{suffix}')
    return (
        "-- Generated by scripts/ai/verify-hamiltonian-cycle.py; do not edit by hand.\n"
        "local moves =\n"
        + "\n".join(move_lines)
        + f"\n\nreturn {{ cols = {cols}, rows = {rows}, moves = moves }}\n"
    )


def choose_food(rng: random.Random, occupied: set[tuple[int, int]], cells: list[tuple[int, int]]):
    open_cells = [cell for cell in cells if cell not in occupied]
    return rng.choice(open_cells) if open_cells else None


def simulate_win(cells: list[tuple[int, int]], seed: int) -> tuple[int, int]:
    rng = random.Random(seed)
    cell_index = {cell: index for index, cell in enumerate(cells)}
    head_index = cell_index[(15, 11)]
    body = deque(cells[(head_index - offset) % len(cells)] for offset in range(4))
    occupied = set(body)
    food = (21, 11)
    if food in occupied:
        food = choose_food(rng, occupied, cells)
    score = 0
    tail_finish_ready = False
    max_steps = len(cells) * len(cells) * 8

    for step_count in range(1, max_steps + 1):
        head_index = (head_index + 1) % len(cells)
        next_head = cells[head_index]
        eating = next_head == food
        entering_tail = next_head == body[-1]
        if next_head in occupied and not (not eating and entering_tail):
            raise AssertionError(f"Seed {seed} collided at step {step_count}.")

        if not eating:
            occupied.remove(body.pop())
        body.appendleft(next_head)
        occupied.add(next_head)

        if tail_finish_ready and entering_tail:
            if len(body) != len(cells) or score != len(cells) - 4:
                raise AssertionError(f"Seed {seed} reached an invalid win state.")
            return score, step_count

        if eating:
            score += 1
            food = choose_food(rng, occupied, cells)
            tail_finish_ready = food is None

    raise AssertionError(f"Seed {seed} did not finish within {max_steps} steps.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate and verify the game's Hamiltonian AI route.")
    parser.add_argument("--path", type=Path, default=Path("."), help="Game repository directory")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--write", action="store_true", help="Write the deterministic Lua route")
    action.add_argument("--check", action="store_true", help="Fail if the Lua route is not current")
    parser.add_argument("--seeds", type=int, default=20, help="Number of full-game simulations")
    args = parser.parse_args()

    if args.seeds < 1:
        parser.error("--seeds must be at least 1")

    cells = build_cycle(COLS, ROWS)
    moves = validate_cycle(cells, COLS, ROWS)
    expected_source = render_lua(moves, COLS, ROWS)
    route_path = args.path.resolve() / ROUTE_FILE

    if args.write:
        route_path.write_text(expected_source, encoding="utf-8", newline="\n")
    else:
        try:
            actual_source = route_path.read_text(encoding="utf-8")
        except FileNotFoundError as error:
            raise SystemExit(f"Missing {route_path}; run this script with --write.") from error
        if actual_source != expected_source:
            raise SystemExit(f"{route_path} is stale; run this script with --write.")

    longest_run = 0
    for seed in range(args.seeds):
        _, steps = simulate_win(cells, seed)
        longest_run = max(longest_run, steps)
    print(f"Verified {len(cells)} cells and {args.seeds} complete games; longest run: {longest_run} steps.")


if __name__ == "__main__":
    main()
